/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

/*
 * マクロを定義する場所。
 * 尚、定数宣言は行わない。
 */
#define WAVE_LED_PORT	GPIOB
#define LED_PORT		GPIOA
#define PSW_PORT		GPIOA
/* マクロ定義完了 */


/*
 * 定数を宣言する場所。
 * 尚、#defineは使わない。
 */
const uint16_t WAVE_LED_BIT = (1 << 7);
const uint16_t LED_BIT = (1 << 11);

const uint16_t PSW_BIT = (1 << 12);
/* 定数宣言完了 */


/*
 * 変数を宣言する場所。
 */
Timer_Handle_t tim16_handle;
Timer_Handle_t tim17_handle;

uint16_t psw_data = 0;

__IO const uint32_t cos_table[] = {0,  0,  0,  0,  0,  0,  1,  1,  1,  2,  2,  3,  4,  5,  5,  6,  7,  8,  9,  10,  11,  12,  14,  15,  16,  18,  19,  21,  22,  24,  25,  27,  29,  31,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  55,  57,  59,  61,  64,  66,  68,  70,  73,  75,  78,  80,  82,  85,  87,  90,  92,  95,  97,  100,  102,  104,  107,  109,  112,  114,  117,  119,  121,  124,  126,  129,  131,  133,  135,  138,  140,  142,  144,  147,  149,  151,  153,  155,  157,  159,  161,  163,  165,  167,  168,  170,  172,  174,  175,  177,  178,  180,  181,  183,  184,  185,  187,  188,  189,  190,  191,  192,  193,  194,  194,  195,  196,  197,  197,  198,  198,  198,  199,  199,  199,  199,  199,  200,  199,  199,  199,  199,  199,  198,  198,  198,  197,  197,  196,  195,  194,  194,  193,  192,  191,  190,  189,  188,  187,  185,  184,  183,  181,  180,  178,  177,  175,  174,  172,  170,  168,  167,  165,  163,  161,  159,  157,  155,  153,  151,  149,  147,  144,  142,  140,  138,  135,  133,  131,  129,  126,  124,  121,  119,  117,  114,  112,  109,  107,  104,  102,  100,  97,  95,  92,  90,  87,  85,  82,  80,  78,  75,  73,  70,  68,  66,  64,  61,  59,  57,  55,  52,  50,  48,  46,  44,  42,  40,  38,  36,  34,  32,  31,  29,  27,  25,  24,  22,  21,  19,  18,  16,  15,  14,  12,  11,  10,  9,  8,  7,  6,  5,  5,  4,  3,  2,  2,  1,  1,  1,  0,  0,  0,  0, 0};
__IO const uint16_t table_length = sizeof(cos_table) / sizeof(cos_table[0]);
__IO uint32_t duty_counter = 0;
__IO uint32_t timer_counter = 0;
/* 変数宣言完了 */


/*
 * 基本関数を宣言する場所。
 * 各種初期設定関数もここで宣言する。
 * 尚、割り込みコールバック関数は別で宣言する。
 */
void Read_Psw(uint16_t *buff);
uint16_t Chattering_Reduction(uint16_t psw);

void Sys_Clock_Conf(void);
static void Timer_Setup(void);
static void IO_Port_Setup(void);
/* 関数宣言完了　*/


/*
 * 基本関数本体を定義する場所。
 * 各種初期設定関数もここに定義する。
 * 尚、割り込みコールバック関数は別で定義する。
 */
void Read_Psw(uint16_t *buff)
{
	uint16_t read_data = ((PSW_PORT->IDR) & PSW_BIT);

	*buff = Chattering_Reduction(read_data);
}

uint16_t Chattering_Reduction(const uint16_t psw)
{
	static uint16_t buff_0, buff_1, Reduction_buffer = 0;

	buff_0 = psw;
	Reduction_buffer &= (buff_0 | buff_1);
	Reduction_buffer |= (buff_0 & buff_1);
	buff_1 = buff_0;

	return Reduction_buffer;
}

int main(void)
{
	uint8_t psw_second_cancel = 0;

	if(System_Config(3U) != Ret_OK)
	{
		Program_Error();
	}

	Sys_Clock_Conf();
	Timer_Setup();
	IO_Port_Setup();

	Timer_Start_IT(&tim16_handle);
	Timer_Start_IT(&tim17_handle);

	while(1)
	{
		if(psw_second_cancel == 0 && (psw_data & PSW_BIT) == PSW_BIT)
		{
			IO_Toggle(LED_PORT, LED_BIT);
			psw_second_cancel++;
		}
		else if(psw_second_cancel != 0 && (psw_data & PSW_BIT) != PSW_BIT)
		{
			psw_second_cancel = 0;
		}
		Program_Delay(1);
	}
}

void Sys_Clock_Conf(void)
{
	OSC_Config_t osc_conf = {0};
	Clock_Config_t clk_conf = {0};

	PWR->CR1 |= 0x01;

	osc_conf.OSC_TYP = (RCC_CR_HSION | RCC_CR_PLLON);
	osc_conf.PLL.PLL_SRC = PLLSRC_HSI;
	osc_conf.PLL.PLL_EN = RCC_PLLCFGR_PLLREN;
	osc_conf.PLL.PLLN = 0x08;
	osc_conf.PLL.PLLM = 0x00;
	osc_conf.PLL.PLLR = 0x01;
	if(OSC_Conf(&osc_conf) != Ret_OK)
	{
		Program_Error();
	}

	clk_conf.APB_PSC = 0x00;
	clk_conf.AHB_PSC = 0x00;
	clk_conf.SysCLK_SRC = RCC_CFGR_SW_1;
	if(CLK_Conf(&clk_conf, 0x02) != Ret_OK)
	{
		Program_Error();
	}
}

static void Timer_Setup(void)
{
	RCC->APBENR2 |= RCC_APBENR2_TIM16EN;

	tim16_handle.Inst = TIM16;
	tim16_handle.TIM_IRQn = TIM16_IRQn;
	tim16_handle.TIM_PSC = (640 - 1);
	tim16_handle.TIM_ARR = (1000 - 1);
	tim16_handle.TIM_CR1 = (TIM_CR1_URS);
	tim16_handle.TIM_CR2 = 0;
	tim16_handle.DMA_IT_MODE = TIM_DIER_UIE;
	if(Timer_Conf(&tim16_handle) != Ret_OK)
	{
		Program_Error();
	}

	RCC->APBENR2 |= RCC_APBENR2_TIM17EN;

	tim17_handle.Inst = TIM17;
	tim17_handle.TIM_IRQn = TIM17_IRQn;
	tim17_handle.TIM_PSC = (64-1);
	tim17_handle.TIM_ARR = (50-1);
	tim17_handle.TIM_CR1 = TIM_CR1_URS;
	tim17_handle.TIM_CR2 = 0;
	tim17_handle.DMA_IT_MODE = TIM_DIER_UIE;
	if(Timer_Conf(&tim17_handle) != Ret_OK)
	{
		Program_Error();
	}
}

static void IO_Port_Setup(void)
{
	IO_Port_Config_t io_conf = {0};

	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;

	io_conf.Inst = GPIOA;
	io_conf.IO_BIT = ((1 << 11) | 1 << 12);
	io_conf.IO_MODE = ((0x1 << GPIO_MODER_MODE11_Pos) | (0x0 << GPIO_MODER_MODE12_Pos));
	io_conf.Out_TYPE = (0x0 << GPIO_OTYPER_OT11_Pos);
	io_conf.Out_SPEED = (0x2 << GPIO_OSPEEDR_OSPEED11_Pos);
	io_conf.PU_PD = (0x2 << GPIO_PUPDR_PUPD12_Pos);
	IO_Port_Conf(&io_conf);

	IO_Write(GPIOA, (1 << 11), IO_RST);


	RCC->IOPENR |= RCC_IOPENR_GPIOBEN;

	io_conf.Inst = GPIOB;
	io_conf.IO_BIT = (1 << 7);
	io_conf.IO_MODE = (0x1 << GPIO_MODER_MODE7_Pos);
	io_conf.Out_TYPE = (0x0 << GPIO_OTYPER_OT7_Pos);
	io_conf.Out_SPEED = (0x2 << GPIO_OSPEEDR_OSPEED7_Pos);
	io_conf.PU_PD = 0;
	IO_Port_Conf(&io_conf);

	IO_Write(GPIOB, (1 << 7), IO_RST);
}
/* 基本関数定義完了 */


/*
 * 割り込みコールバック関数本体を定義する場所。
 * 割り込みルーチン内で処理したい機能をここに実装する。
 *
 * <重要事項>
 * 各コールバック関数内で別の割り込みを使用しない事。
 */
void Timer_Period_Callback(Timer_Handle_t *timer_handle)
{
	if((timer_handle->Inst) == TIM16)
	{
		Read_Psw(&psw_data);
	}

	if((timer_handle->Inst) == TIM17)
	{
		static uint32_t duty = 0;

		duty = cos_table[duty_counter];
		if(200 > timer_counter && timer_counter >= duty)
		{
			IO_Write(WAVE_LED_PORT, WAVE_LED_BIT, IO_RST);
		}
		else if(duty > timer_counter && timer_counter >= 0)
		{
			IO_Write(WAVE_LED_PORT, WAVE_LED_BIT, IO_SET);
		}

		timer_counter++;
		if(timer_counter > 200)
		{
			timer_counter = 0;

			duty_counter++;
			if(duty_counter >= table_length)
			{
				duty_counter = 0;
			}
		}
	}
}
/* 割り込みコールバック関数定義完了 */


/*
 * エラー処理関数本体を定義する場所。
 * ステータスエラー時等の処理をここでする。
 */
void Program_Error(void)
{
	__disable_irq();
	while(1);
}
/* エラー処理関数定義完了 */
